### ISSUE TITLE
Symfony3 support?

### ISSUE THREAD

**Issue by fleskalebas** [DATA-DOG/DataDogPagerBundle#8]
Hello,

When I change my composer.json to update to Symfony3, I get the error about the framework-bundle version. DataDog requires ~2.3, the composer.json of symfony 3 want ^3.0.2.

Is support coming in the near future or do I have to try KnpPaginatorBundle? :)

**Comment by l3pp4rd** [comment]
hi, update your composer

**Comment by fleskalebas** [comment]
Wonderful, thanks!
